export const mockSubDivision = [
  {
    id: 1,
    name: "Phòng họp tầng 3",
    objects: [
      {
        id: 1,
        name: "Bàn: gỗ thịt",
        unit: "Chiếc",
        mass: 3,
        note: "",
      },
      {
        id: 2,
        name: "Bàn: inox",
        unit: "Chiếc",
        mass: 5,
        note: "",
      },
      {
        id: 3,
        name: "Gạch ốp: đá marble",
        unit: "m2",
        mass: 50,
        note: "",
      },
      {
        id: 4,
        name: "Lan can: sắt (phủ sơn)",
        unit: "m2",
        mass: 0.5,
        note: "",
      },
    ],
  },
  {
    id: 2,
    name: "Sân thượng",
    objects: [
      {
        id: 1,
        name: "Bàn: gỗ thịt",
        unit: "Chiếc",
        mass: 3,
        note: "",
      },
      {
        id: 2,
        name: "Bàn: inox",
        unit: "Chiếc",
        mass: 5,
        note: "",
      },
      {
        id: 3,
        name: "Gạch ốp: đá marble",
        unit: "m2",
        mass: 50,
        note: "",
      },
      {
        id: 4,
        name: "Lan can: sắt (phủ sơn)",
        unit: "m2",
        mass: 0.5,
        note: "",
      },
    ],
  },
  {
    id: 3,
    name: "Tiểu bộ phận rỗng",
    objects: null,
  },
];

export const buildingObject = [
  { id: 1, name: "Ấm chén: men xứ", unit: "Bộ" },
  { id: 2, name: "Bậc thang: xi măng", unit: "Bậc" },
  { id: 3, name: "Bậc thang: gạch men", unit: "Bậc" },
  { id: 4, name: "Bậc thang: nhựa", unit: "Bậc" },
  { id: 5, name: "Bậc thang: sắt (quét sơn )", unit: "Tầng" },
  { id: 6, name: "Bậc thang: đá granito", unit: "Bậc" },
  { id: 7, name: "Bậc thang: sơn eboxy", unit: "Bậc" },
  { id: 8, name: "Bàn: gỗ công nghiệp", unit: "m2" },
  { id: 9, name: "Bàn: inox", unit: "Chiếc" },
  { id: 10, name: "Bàn: dán focmeca", unit: "Chiếc" },
  { id: 11, name: "Bàn: gỗ thịt", unit: "Chiếc" },
  { id: 12, name: "Ban công: kính", unit: "m2" },
  { id: 13, name: "Ban công: sắt", unit: "m2" },
  { id: 14, name: "Ban công: inox", unit: "m2" },
  { id: 15, name: "Sàn: gạch men", unit: "m2" },
  { id: 16, name: "Sàn: ceramic", unit: "m2" },
  { id: 17, name: "Sàn: gạch đỏ", unit: "m2" },
  { id: 18, name: "Sàn: xi măng", unit: "m2" },
  { id: 19, name: "Sàn: sơn PU", unit: "m2" },
  { id: 20, name: "Sàn: granito", unit: "m2" },
  { id: 21, name: "Sàn: granite tự nhiên", unit: "m2" },
  { id: 22, name: "Sàn: granite nhân tạo", unit: "m2" },
  { id: 23, name: "Bồn cầu: men sứ", unit: "Cái" },
  { id: 24, name: "Bồn tiểu: men sứ", unit: "Cái" },
  { id: 25, name: "Ốp chân tường: đá marble", unit: "m2" },
  { id: 26, name: "Ốp chân tường: đá granite", unit: "m2" },
  { id: 27, name: "Ốp chân tường: gạch men", unit: "m2" },
  { id: 28, name: "Ốp chân tường: tường sơn.", unit: "m2" },
  { id: 29, name: "Ốp chân tường:", unit: "m2" },
  { id: 30, name: "Chậu cây: men sứ", unit: "m2" },
  { id: 31, name: "Chậu rửa: men sứ", unit: "Cái" },
  { id: 32, name: "Cốc chén: men sứ", unit: "Cái" },
  { id: 33, name: "Cốc chén: thủy tinh", unit: "Cái" },
  { id: 34, name: "Cửa: gỗ", unit: "m2" },
  { id: 35, name: "Cửa: Sắt (phun sơn)", unit: "m2" },
  { id: 36, name: "Cửa: khung nhôm kính", unit: "m2" },
  { id: 37, name: "Cửa: kính", unit: "m2" },
  { id: 38, name: "Cửa: inox", unit: "m2" },
  { id: 39, name: "Cửa sổ: Sắt (phun sơn)", unit: "m2" },
  { id: 40, name: "Cửa sổ: inox", unit: "m2" },
  { id: 41, name: "Cửa sổ: nhôm kính", unit: "m2" },
  { id: 42, name: "Gạch ốp: men sứ", unit: "m2" },
  { id: 43, name: "Gạch ốp: đá marble", unit: "m2" },
  { id: 44, name: "Gạch ốp: đá granite", unit: "m2" },
  { id: 45, name: "Gạch ốp: amilu", unit: "m2" },
  { id: 46, name: "Ghế: gỗ", unit: "Cái" },
  { id: 47, name: "Ghế: nỉ", unit: "Cái" },
  { id: 48, name: "Ghế: da", unit: "Cái" },
  { id: 49, name: "Ghế: inox", unit: "Cái" },
  { id: 50, name: "Ghế: sắt phun sơn đệm da", unit: "Cái" },
  { id: 51, name: "Gờ: nhôm kính", unit: "m2" },
  { id: 52, name: "Gờ: sơn xi măng", unit: "m2" },
  { id: 53, name: "Gờ:", unit: "m2" },
  { id: 54, name: "Gương: kinh", unit: "m2" },
  { id: 55, name: "Gương: kính khung gỗ", unit: "m2" },
  { id: 56, name: "Gương: kính khung nhôm", unit: "m2" },
  { id: 57, name: "Khung: nhôm", unit: "m" },
  { id: 58, name: "Khung: gỗ", unit: "m" },
  { id: 59, name: "Khung: inox", unit: "m" },
  { id: 60, name: "Kính: cường lực", unit: "m2" },
  { id: 61, name: "Kính: thường", unit: "m2" },
  { id: 62, name: "Kính: kính dán lớp chống nắng", unit: "m2" },
  { id: 63, name: "Mạng nhện:", unit: "m2" },
  { id: 64, name: "Ổ điện: nhựa", unit: "Cái" },
  { id: 65, name: "Ốp tường: gạch men", unit: "m2" },
  { id: 66, name: "Ốp tường: đá granite", unit: "m2" },
  { id: 67, name: "Ốp tường: đá marble", unit: "m2" },
  { id: 68, name: "Ốp tường: amilu", unit: "m2" },
  { id: 69, name: "Quầy: gỗ", unit: "m2" },
  { id: 70, name: "Quầy: phoocmica", unit: "m2" },
  { id: 71, name: "Rèm: vải", unit: "m2" },
  { id: 72, name: "Rèm: nhựa", unit: "m2" },
  { id: 73, name: "Rèm: gỗ", unit: "m2" },
  { id: 74, name: "Thảm: Gai", unit: "m2" },
  { id: 75, name: "Thảm: len", unit: "m2" },
  { id: 76, name: "Thảm: nhựa", unit: "m2" },
  { id: 77, name: "Thang máy: inox", unit: "m2" },
  { id: 78, name: "Thang máy: kính", unit: "m2" },
  { id: 79, name: "Thùng rác: nhựa", unit: "lít" },
  { id: 80, name: "Trần: thạch cao", unit: "m2" },
  { id: 81, name: "Trần: gỗ", unit: "m2" },
  { id: 82, name: "Tủ: sắt", unit: "m2" },
  { id: 83, name: "Tủ: Gỗ", unit: "m2" },
  { id: 84, name: "Tủ: nhôm kính", unit: "m2" },
  { id: 85, name: "Vách ngăn: phoocmica", unit: "m2" },
  { id: 86, name: "Vòi: inox", unit: "Cái" },
  { id: 87, name: "Vòi: kẽm", unit: "Cái" },
  { id: 88, name: "Barie : sắt (quét sơn )", unit: "m2" },
  { id: 89, name: "Biển báo: nhựa cứng", unit: "m2" },
  { id: 90, name: "Biển báo: tôn phủ sơn", unit: "m2" },
  { id: 91, name: "Bình cứu hỏa: thép (phủ sơn)", Cunit: "ái" },
  { id: 92, name: "Bốt bảo vệ: khung nhôm kính", unit: "m2" },
  { id: 93, name: "Bục: gỗ", unit: "m2" },
  { id: 94, name: "Bục: inox", unit: "m2" },
  { id: 95, name: "Chấn song: sắt (phun sơn)", unit: "m2" },
  { id: 96, name: "Chấn song: inox", unit: "m2" },
  { id: 97, name: "Chớp kính: kính", unit: "m2" },
  { id: 98, name: "Chớp kính: nhôm", unit: "m2" },
  { id: 99, name: "Cống: sắt", unit: "m2" },
  { id: 100, name: "Cống: xi măng", unit: "m2" },
  { id: 101, name: "Cổng: sắt", unit: "m2" },
  { id: 102, name: "Cổng: inox", unit: "m2" },
  { id: 103, name: "Cột: bê tông", unit: "m2" },
  { id: 104, name: "Cột: sắt", unit: "m2" },
  { id: 105, name: "Đèn báo: kính", unit: "Cái" },
  { id: 106, name: "Đường ống: Sắt (phun sơn)", unit: "m" },
  { id: 107, name: "Đường ống: nhựa PVC", unit: "m" },
  { id: 108, name: "Đường ống: kẽm", unit: "m" },
  { id: 109, name: "Hố ga: xi măng", unit: "Cái" },
  { id: 110, name: "Lan can: inox", unit: "m2" },
  { id: 111, name: "Lan can: sắt (phủ sơn)", unit: "m2" },
  { id: 112, name: "Mái: inox", unit: "m2" },
  { id: 113, name: "Mái: sắt", unit: "m2" },
  { id: 114, name: "Mái: kính", unit: "m2" },
  { id: 115, name: "Tiểu cảnh: đá", unit: "m2" },
  { id: 116, name: "Tiểu cảnh: sàn xi măng", unit: "m2" },
  { id: 117, name: "Tiểu cảnh: ốp gạch men", unit: "m2" },
];

export const buildingObjName = () => {
  const arr = []
  for (const property in buildingObject) {
    arr.push(buildingObject[property].name)
  }
  return arr
}
