export const mockUsers = [
  {
    key: 10101,
    username: "MONOCHROME_STAFFS",
    roles: "staff",
    phone: "0353119808",
  },
];

export const mockContracts = [
  {
    key: 1,
    customer_name: "Viện Đào Tạo và Nghiên Cứu BIDV",
    document_id: "1003/2020/ ĐTNC - HM",
    appendices_number: 0,
    customer_city: "Hà Nội",
    address: "733 đường Hồng Hà",
    type: "Trường học",
    effectiveTimeFrom: 1606928400000,
    effectiveTimeTo: 1609606800000,
    duration_month: "12",
    value: null,
    contractValue: '416328000',
    human_resources: null,
    human_resources_weekend: false,
    sub_department: null,
    file_id: 5.1,
    content: "Hợp đồng làm sạch",
    subject_count: 11,
    year: 2021,
    value_per_person: "######",
    file: "ĐTNC-HM.docx",
    status: "success",
  },
  {
    key: 2,
    customer_name: "Viện Đào Tạo và Nghiên Cứu BIDV",
    document_id: "1003/2020/ ĐTNC - HM",
    appendices_number: 0,
    customer_city: "Hà Nội",
    address: "733 đường Hồng Hà",
    type: "Trường học",
    effectiveTimeFrom: 1604928400000,
    effectiveTimeTo: 1609676800000,
    duration_month: "12",
    value: null,
    contractValue: '763927631',
    human_resources: null,
    human_resources_weekend: false,
    sub_department: null,
    file_id: 5.1,
    content: "Hợp đồng làm sạch",
    subject_count: 11,
    year: 2021,
    value_per_person: "######",
    file: "ĐTNC-HM.docx",
    status: "pending",
  },
  {
    key: 3,
    customer_name: "Viện Đào Tạo và Nghiên Cứu BIDV",
    document_id: "1003/2020/ ĐTNC - HM",
    appendices_number: 0,
    customer_city: "Hà Nội",
    address: "733 đường Hồng Hà",
    type: "Trường học",
    effectiveTimeFrom: 1601928400000,
    effectiveTimeTo: 1601606800000,
    duration_month: "12",
    value: null,
    contractValue: '2648173843',
    human_resources: null,
    human_resources_weekend: false,
    sub_department: null,
    file_id: 5.1,
    content: "Hợp đồng làm sạch",
    subject_count: 11,
    year: 2021,
    value_per_person: "######",
    file: "ĐTNC-HM.docx",
    status: "unrequest",
  },
  {
    key: 4,
    customer_name: "Viện Đào Tạo và Nghiên Cứu BIDV",
    document_id: "1003/2020/ ĐTNC - HM",
    appendices_number: 0,
    customer_city: "Hà Nội",
    address: "733 đường Hồng Hà",
    type: "Trường học",
    effectiveTimeFrom: 1604928400000,
    effectiveTimeTo: 1612606800000,
    duration_month: "12",
    value: null,
    contractValue: '120121212',
    human_resources: null,
    human_resources_weekend: false,
    sub_department: null,
    file_id: 5.1,
    content: "Hợp đồng làm sạch",
    subject_count: 11,
    year: 2021,
    value_per_person: "######",
    file: "ĐTNC-HM.docx",
    status: "success",
  },
  {
    key: 5,
    customer_name: "Viện Đào Tạo và Nghiên Cứu BIDV",
    document_id: "1003/2020/ ĐTNC - HM",
    appendices_number: 0,
    customer_city: "Hà Nội",
    address: "733 đường Hồng Hà",
    type: "Trường học",
    effectiveTimeFrom: 1616928400000,
    effectiveTimeTo: 1699606800000,
    duration_month: "12",
    value: null,
    contractValue: '50014142314',
    human_resources: null,
    human_resources_weekend: false,
    sub_department: null,
    file_id: 5.1,
    content: "Hợp đồng làm sạch",
    subject_count: 11,
    year: 2021,
    value_per_person: "######",
    file: "ĐTNC-HM.docx",
    status: "reject",
  },
];

export const dashboardByTimes = {
  "7days": {
    employee: 75,
    turnover: "235.000.000 VNĐ",
    expire: 0,
  },
  "30days": {
    employee: 83,
    turnover: "791.380.000 VNĐ",
    expire: 1,
  },
  "60days": {
    employee: 141,
    turnover: "1.335.902.000 VNĐ",
    expire: 2,
  },
  "90days": {
    employee: 207,
    turnover: "1.715.355.000 VNĐ",
    expire: 3,
  },
};
